version: '3'
services:
  frisbeer-backend:
    container_name: frisbeer-backend
    image: frisbeer-backend
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static-content:/var/www/frisbeer/static:rw
    restart: unless-stopped

  db:
    container_name: frisbeer-db
    image: postgres:11
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <password>
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frisbeer-nginx:
    container_name: frisbeer-nginx
    build:
      context: ..
      dockerfile: docker/Nginx
    links:
    - frisbeer-backend
    volumes:
      - static-content:/var/www/frisbeer/static:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pg-data:
  static-content:
