version: '3'
services:
  frisbeer-backend:
    image: frisbeer-backend
    depends_on:
      - db
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - static-content:/var/www/frisbeer.win/static:rw

  db:
    image: postgres:11

  frisbeer-nginx:
    build:
      context: ..
      dockerfile: docker/Nginx
    links:
    - frisbeer-backend
    volumes:
      - static-content:/var/static:ro
    ports:
      - "8080:8080"

volumes:
  static-content:
