# Generated by Django 3.0.14 on 2021-12-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0034_season_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elo_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='score_algorithm',
            field=models.CharField(choices=[('2017', 'Season 2017'), ('2018', 'Season 2018'), ('elo', 'Elo'), ('top_elo', 'Best elo')], max_length=255),
        ),
    ]
